# Build the manager binary
# FROM golang:1.17 as builder

# WORKDIR /workspace
# # Copy the Go Modules manifests
# COPY go.mod go.mod
# COPY go.sum go.sum
# # cache deps before building and copying source so that we don't need to re-download as much
# # and so that source changes don't invalidate our downloaded layer
# RUN go mod download

# # Copy the go source
# COPY main.go main.go
# COPY api/ api/
# COPY controllers/ controllers/

# # Build
# RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o manager main.go

# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM acr.aishu.cn/public/ubuntu:20.10.20210510

RUN groupadd -r -g 1001 mongodb && useradd -r -u 1001 -g mongodb mongodb

ADD config/config /root/.kube/config
COPY manager manager

RUN chown -R mongodb:mongodb /root /root/.kube /root/.kube/config;\
    chmod 700  /root/.kube/config;
WORKDIR /


#COPY --from=builder /workspace/manager .
USER mongodb

#ENTRYPOINT ["/manager"]
