
apiVersion: v1
kind: ConfigMap
metadata:
  name: mymongodb-sample
  namespace: default
data:
  mongodb.conf: |
    net:
      bindIpAll: true
      maxIncomingConnections: 10000
      tls:
        mode: disabled
      unixDomainSocket:
        pathPrefix: /data/mongodb_data
      serviceExecutor: adaptive
    operationProfiling:
      mode: slowOp
      slowOpThresholdMs: 1000
    processManagement:
      pidFilePath: /data/mongodb_data/mongodb.pid
    storage:
      dbPath: /data/mongodb_data
      directoryPerDB: true
      engine: wiredTiger
      wiredTiger:
        engineConfig:
          cacheSizeGB: 4
          directoryForIndexes: true
    security:
      javascriptEnabled: false
    systemLog:
      destination: file
      logAppend: false
      logRotate: rename
      path: /data/mongodb_data/mongodb.log
      quiet: true
      traceAllExceptions: false
---
apiVersion: customgroup.jmongodb.crd.com/v1
kind: Mymongodb
metadata:
  name: mymongodb-sample
  namespace: default
  labels:
    app: mymongodb-sample
spec:
  # TODO(user): Add fields here
  replicas: 2
  selector:
    matchLabels:
      app: mymongodb-sample
  template:
    metadata:
      labels:
        app: mymongodb-sample
    spec:
      containers:
      - name: mongodb
        image: acr.aishu.cn/proton/mongodb:1.10.2
        imagePullPolicy: IfNotPresent
        args:
        - mongod
        - "--config"
        - "/mongodb/config/mongodb.conf"
        - "--port"
        - "28000"
        - "--auth"
        - "--keyFile"
        - "/mongodb/config/mongodb.keyfile"
        - "--replSet"
        - "rs0"
        ports:
        - name: mongodb
          containerPort: 28000
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "ZWlzb28uY29tMTIz"
        - name: MONGODB_PORT
          value: "28000"
        - name: TRACE
          value: "false"
        - name: TZ
          value: "Asia/Shanghai"
        - name: REPLSET_NAME
          value: "rs0"
        volumeMounts:
        - name: mongodb-conf
          mountPath: /mongodb/config/mongodb.conf
          subPath: mongodb.conf
      volumes:
      - name: mongodb-conf
        configMap:
          name: mymongodb-sample
          items:
          - key: mongodb.conf
            path: mongodb.conf
  relationResource:
    serviceInfo:
      type: NodePort
      ports:
      - name: mymongodb-sample
        port: 28000
        nodePort: 30000
